name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Test Secrets
        run: |
          echo "Host: ${{ secrets.AWS_HOST }}"
          echo "User: ${{ secrets.AWS_USER }}"
          # echo "Key: ${{ secrets.AWS_KEY }}"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            if [ -d "dist" ]; then
              sudo rm -rf /var/www/html/*
              sudo cp -r build/* /var/www/html/
            else
              echo "Build directory does not exist."
            fi
          debug: true
